version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app
  django_app:
    image: django_app
    build:
      context: ./emunDjango
    container_name: "django_cont"
    ports:
      - 8001:8001
    command: gunicorn emun.wsgi --bind 0.0.0.0:8001
    env_file:
      - "./emunDjango/.env"
    depends_on:
      - db
  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=emun_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql